### ISSUE TITLE
it doesn't display japanese

### ISSUE THREAD

**Issue by dwang888** [pvthuy/word2vec-visualization#1]
when i tried to search Japanese word, it never showed any result; English works

**Comment by pvthuy** [comment]
Can you inspect elements using Chrome/Opera, etc. to see the problem?

**Comment by dwang888** [comment]
I tried IE10, Chrome, and Firefox, none of them worked in Japanese. I also tried Simplified Chinese, it also had same issue with. 
Detail: when I click 'search' button, no response, and no error message like 'word not found'. Please advise. Thanks.

**Comment by dwang888** [comment]
update: solution
Probably I found the solution and root cause. Everyword in json data file should have corresponding synonyms in the same file, otherwise, it won't display any result. e.g.

"raining":[
{"w":"unbelievably","d":0.355},
{"w":"soya","d":0.355},
{"w":"snowy","d":0.354},

if we change 'soya' to 'soya123', which is not an entry and doesn't have synonyms in this file (of course, 'soya123' is made by us and doesn't have similar meaning word), then it will blow up the whole process.

Solution: make sure you run the python completely to create a complete json file.
