### ISSUE TITLE
Dynamically change the number of similar words and the depth of tree

### ISSUE THREAD

**Issue by pvthuy** [pvthuy/word2vec-visualization#12]
In the current code, the maximum number of similar words (_N_) given the input is fixed to _**20**_. It is desirable to automatically generate the JSON structure, e.g., for _N_ >10.
Also, the maximum value of the depth of tree is just _5_ currently.

**Comment by pvthuy** [comment]
@massongit Want to try?

**Comment by massongit** [comment]
@pvthuy I may take several months to complete this issue, but if that's okay then I want to try it.

**Comment by massongit** [comment]
@pvthuy Please give a concrete example of dynamically change the number of similar words.
